# To generate graphql_api.md, go to the pydocmd folder and run:
# graphql-markdown --no-toc --title 'Daptics GraphQL API' api-<version>.json >graphql_api.md
#
# To generate python_client.md, go to the python_client folder and run:
# pdoc --pdf --force --template-dir ../pdoc/templates daptics_client >../pydocmd/daptics_client.md
site_name: Daptics Python Client
site_url: https://protolife.github.io/daptics-api/
nav:
  - Daptics API Index: index.md
  - Python API Client: daptics_client.md
  - Daptics GraphQL API: graphql_api.md
  - Jupyter Notebooks: jupyter_notebooks.md
docs_dir: ./pydocmd
site_dir: ./docs # Required for GitHub Pages
theme:
  name: "rtd-dropdown"
  navigation_depth: 3
  collapse_navigation: false
